# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cf99d45c5900bf003bc38e247b5d58aaef384b98aa89ba964c7065f1be127bafbe03409674287475011b6572b382b26158bedf1069f9773a4856d33029aed4c

test:
  secret_key_base: ef7a2b1641c641e44a81fd5198e4a9a771f3525bda81c80797a94183a881ada32f946f6600c6db9aa81105071412f2e63558d79d0a324b7c27d6fb3f3226c133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
